import '../../data/models/wellness_data_model.dart';

/// Structured daily recommendation generated by the centralized engine.
class WellnessRecommendation {
  final WellnessMode mode;
  final String modeLabel;
  final String explanation;
  final String tag;

  const WellnessRecommendation({
    required this.mode,
    required this.modeLabel,
    required this.explanation,
    required this.tag,
  });
}

/// Centralized Daily Recommendation Engine
/// 
/// Takes ONE consistent daily Wellness Score and autonomic signals,
/// and computes the user's recommended daily operational mode:
/// RECOVER, STEADY, or PUSH, along with a personalized explanation.
class WellnessRecommendationEngine {
  const WellnessRecommendationEngine._();

  static WellnessRecommendation compute({
    required int wellnessScore,
    int? readinessScore,
    int? hrvMs,
    int? restHr,
    double? sleepHours,
  }) {
    if (wellnessScore <= 0 && (readinessScore == null || readinessScore <= 0)) {
      return const WellnessRecommendation(
        mode: WellnessMode.steady,
        modeLabel: 'Steady',
        explanation: 'Awaiting biometric telemetry to generate your personalized daily guidance.',
        tag: 'No data',
      );
    }

    final int effectiveScore = wellnessScore > 0 ? wellnessScore : (readinessScore ?? 65);

    if (effectiveScore >= 75) {
      final String extraSignal = (hrvMs != null && hrvMs > 55)
          ? ' Elevated HRV indicates high autonomic reserve.'
          : (sleepHours != null && sleepHours >= 7.5)
              ? ' Solid restorative sleep has restored your neuromuscular capacity.'
              : '';

      return WellnessRecommendation(
        mode: WellnessMode.push,
        modeLabel: 'Push',
        explanation: "Your recovery signals are strong today, so you're ready for a higher-intensity day.$extraSignal",
        tag: 'Push day',
      );
    } else if (effectiveScore >= 50) {
      final String extraSignal = (restHr != null && restHr > 0 && restHr <= 68)
          ? ' Resting heart rate is stable near your baseline.'
          : '';

      return WellnessRecommendation(
        mode: WellnessMode.steady,
        modeLabel: 'Steady',
        explanation: "Your vitals are balanced and steady. Maintain consistency with moderate aerobic and movement effort.$extraSignal",
        tag: 'Steady day',
      );
    } else {
      final String extraSignal = (sleepHours != null && sleepHours < 6.0)
          ? ' Sleep debt is elevated.'
          : (hrvMs != null && hrvMs < 35)
              ? ' Sympathetic activation indicates residual fatigue.'
              : '';

      return WellnessRecommendation(
        mode: WellnessMode.recover,
        modeLabel: 'Recover',
        explanation: "Your body may benefit from a lighter day focused on recovery, restorative walks, and soft-tissue release.$extraSignal",
        tag: 'Recover day',
      );
    }
  }
}
