import '../../data/models/wellness_data_model.dart';

/// Structured daily recommendation generated by the centralized engine.
class WellnessRecommendation {
  final WellnessMode mode;
  final String modeLabel;
  final String explanation;
  final String tag;

  const WellnessRecommendation({
    required this.mode,
    required this.modeLabel,
    required this.explanation,
    required this.tag,
  });
}

/// Centralized Daily Recommendation Engine
/// 
/// Takes ONE consistent daily Wellness Score and autonomic signals,
/// and computes the user's recommended daily operational mode:
/// RECOVER, STEADY, or PUSH, along with a personalized explanation.
class WellnessRecommendationEngine {
  const WellnessRecommendationEngine._();

  static WellnessRecommendation compute({
    required int wellnessScore,
    int? readinessScore,
    int? hrvMs,
    int? restHr,
    double? sleepHours,
  }) {
    if (wellnessScore <= 0 && (readinessScore == null || readinessScore <= 0)) {
      return const WellnessRecommendation(
        mode: WellnessMode.steady,
        modeLabel: 'Steady',
        explanation: 'Awaiting biometric telemetry to generate your personalized daily guidance.',
        tag: 'No data',
      );
    }

    final int effectiveScore = wellnessScore > 0 ? wellnessScore : (readinessScore ?? 65);

    if (effectiveScore >= 75) {
      return const WellnessRecommendation(
        mode: WellnessMode.push,
        modeLabel: 'Push',
        explanation: 'Your recovery signals are strong today. You are fully primed for higher-intensity training.',
        tag: 'Push day',
      );
    } else if (effectiveScore >= 50) {
      return const WellnessRecommendation(
        mode: WellnessMode.steady,
        modeLabel: 'Steady',
        explanation: 'Your vitals are balanced and steady. Maintain consistency with moderate aerobic movement.',
        tag: 'Steady day',
      );
    } else {
      return const WellnessRecommendation(
        mode: WellnessMode.recover,
        modeLabel: 'Recover',
        explanation: 'Your body will benefit from a lighter recovery day with gentle walks, mobility, and rest.',
        tag: 'Recover day',
      );
    }
  }
}
